version: "3.8"

services:

  book_db_go:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database-data-go:/var/lib/postgresql/data/ # persist data even if container shuts down
    environment:
      POSTGRES_USER: "bookuser"
      POSTGRES_PASSWORD: "bookdbpass"
      POSTGRES_DB: "books_db"
    
  redis_books_db_go:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"

  # book-api-go-fiber:
  #   image: fiber-api:latest
  #   build: .
  #   ports: 
  #     - 3000-3008:3000
  #   depends_on: 
  #     - book_db_go
  #   links: 
  #     - "book_db_go:database"
  #   command: sh -c "sleep 1 && /dist/main"
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     resources:
  #       limits:
  #         cpus: '0.001'
  #         memory: 80M
  #       reservations:
  #         cpus: '0.0001'
  #         memory: 20M
  #         ## NOT SURE if this is even working... CTOP is not displaying 20Mb for each container

  # loadbalancer:
  #   image: dockercloud/haproxy
  #   links:
  #     - book-api-go-fiber
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
    

volumes: 
    database-data-go: